#!/usr/bin/env node
/**
 * embed-fonts.js
 *
 * Writes @font-face rules with base64 `data:` URIs into shared/retro.css.
 *
 * WHY THIS EXISTS RATHER THAN A <link> TO GOOGLE FONTS
 *
 * AESTHETIC_GUIDE.md §3.2: a <link> to fonts.googleapis.com does not exist on
 * a double-clicked page with no network, so it silently falls back to Courier
 * New in exactly the scenario the file:// hard constraint protects.
 * `under-development/javelin-battle/javelin-battle.html` has that bug today.
 *
 * A `data:` URI has no relative path to resolve and no network to reach, which
 * is the only form that survives file://.
 *
 * USAGE
 *
 *   1. Put the two .woff2 files in shared/fonts/:
 *        PressStart2P-Regular.woff2
 *        VT323-Regular.woff2
 *      Both are SIL Open Font License, so embedding and redistributing them in
 *      this repo is fine. Keep shared/fonts/OFL.txt alongside them.
 *
 *   2. node scripts/embed-fonts.js
 *
 * Run from the repo root. Idempotent: it replaces whatever sits between the
 * RETRO-FONTS markers, so re-running after swapping a font file just works.
 *
 * SIZE. The guide budgets ~10-14 KB per face subset, ~40 KB for both. base64
 * inflates by 4/3, so a full unsubsetted VT323 will blow past that. If the
 * total lands well above ~60 KB, subset to `A-Z a-z 0-9` plus punctuation
 * (pyftsubset from fonttools) before embedding — every stack in retro.css
 * declares a real fallback precisely so a subset that lacks a glyph degrades
 * instead of showing tofu.
 */

const fs = require("fs");
const path = require("path");

const CSS = path.join("shared", "retro.css");
const FONT_DIR = path.join("shared", "fonts");

const FACES = [
  { family: "Press Start 2P", file: "PressStart2P-Regular.woff2", weight: 400, style: "normal" },
  { family: "VT323", file: "VT323-Regular.woff2", weight: 400, style: "normal" }
];

const BEGIN = "/* RETRO-FONTS:BEGIN */";
const END = "/* RETRO-FONTS:END */";

function main() {
  if (!fs.existsSync(CSS)) {
    console.error(`Not found: ${CSS}. Run this from the repo root.`);
    process.exit(1);
  }

  const missing = FACES.filter((f) => !fs.existsSync(path.join(FONT_DIR, f.file)));
  if (missing.length) {
    console.error("Missing font file(s):\n");
    for (const f of missing) console.error(`  ${path.join(FONT_DIR, f.file)}`);
    console.error(
      "\nBoth faces are SIL Open Font License and available from Google Fonts:\n" +
      "  https://fonts.google.com/specimen/Press+Start+2P\n" +
      "  https://fonts.google.com/specimen/VT323\n\n" +
      "Download the .woff2, put them in shared/fonts/, and re-run.\n" +
      "Until then retro.css falls back to Courier New, which is why every stack\n" +
      "in it declares a real fallback. Nothing is broken without this."
    );
    process.exit(1);
  }

  let blocks = [
    "/* Generated by scripts/embed-fonts.js — do not hand-edit.",
    " * Both faces are SIL Open Font License; see shared/fonts/OFL.txt.",
    " * font-display: block, not swap — a flash of Courier is worse than a beat",
    " * of nothing (AESTHETIC_GUIDE.md §3.2). */"
  ].join("\n");

  let total = 0;
  for (const f of FACES) {
    const buf = fs.readFileSync(path.join(FONT_DIR, f.file));
    const b64 = buf.toString("base64");
    total += b64.length;
    blocks +=
      `\n@font-face {\n` +
      `    font-family: '${f.family}';\n` +
      `    font-style: ${f.style};\n` +
      `    font-weight: ${f.weight};\n` +
      `    font-display: block;\n` +
      `    src: url(data:font/woff2;base64,${b64}) format('woff2');\n` +
      `}\n`;
    console.log(`  ${f.family.padEnd(16)} ${(buf.length / 1024).toFixed(1)} KB raw -> ${(b64.length / 1024).toFixed(1)} KB base64`);
  }

  const css = fs.readFileSync(CSS, "utf8");
  const i = css.indexOf(BEGIN);
  const j = css.indexOf(END);
  if (i < 0 || j < 0 || j < i) {
    console.error(`Markers ${BEGIN} / ${END} not found in ${CSS}. Restore them and re-run.`);
    process.exit(1);
  }

  const out = css.slice(0, i + BEGIN.length) + "\n" + blocks + css.slice(j);
  fs.writeFileSync(CSS, out, "utf8");

  const kb = total / 1024;
  console.log(`\nEmbedded into ${CSS}: ${kb.toFixed(1)} KB of base64.`);
  if (kb > 60) {
    console.log(
      "\nThat is above the ~40 KB the guide budgets. Consider subsetting to\n" +
      "A-Z a-z 0-9 + punctuation with pyftsubset and re-running."
    );
  }
}

main();
